const $=s=>document.querySelector(s);
const state={manifest:null,rows:[],filtered:[],page:1,size:40,mode:'year',request:0,cache:new Map()};
const aliases={'长征':'chang zheng','猎鹰':'falcon','联盟':'soyuz','阿波罗':'apollo','神舟':'shenzhou','天舟':'tianzhou','旅行者':'voyager','斯普特尼克':'sputnik','拜科努尔':'baikonur','酒泉':'jiuquan','库鲁':'kourou'};
function el(tag,value,cls){const n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(cls)n.className=cls;return n;}
async function json(path){const r=await fetch(path);if(!r.ok)throw Error(`读取 ${path} 失败（${r.status}）`);if(path.endsWith('.gz')){if(!globalThis.DecompressionStream)throw Error('浏览器不支持解压，请使用新版 Chrome、Edge 或 Firefox');return new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json();}return r.json();}
async function yearData(y){if(state.cache.has(y))return state.cache.get(y);const shard=state.manifest.yearShards.find(x=>x.years.includes(Number(y)));if(!shard)throw Error(`没有找到 ${y} 年数据分片`);const grouped=await json(`archive/${shard.file}`);for(const [year,rows] of Object.entries(grouped))state.cache.set(Number(year),rows);return state.cache.get(Number(y));}
function options(id,values){const n=$(id);n.replaceChildren(new Option('全部',''));for(const v of [...new Set(values)].filter(Boolean).sort())n.add(new Option(v,v));}
async function load(all=false){const ticket=++state.request;$('#status').textContent=all?'正在载入全库索引…':'正在读取年份档案…';try{const rows=all?(await Promise.all(state.manifest.searchShards.map(x=>json(`archive/${x.file}`)))).flat():await yearData(Number($('#year').value));if(ticket!==state.request)return;state.rows=rows;state.mode=all?'all':'year';options('#type',rows.map(x=>x.actionType||x.t));options('#result',rows.map(x=>x.result));apply();}catch(e){if(ticket===state.request)$('#status').textContent=e.message;}}
function apply(){const terms=$('#q').value.toLowerCase().trim().split(/\s+/).filter(Boolean);state.filtered=state.rows.filter(x=>{const hay=[x.search,x.q,x.id,x.vehicle,x.v,x.flight,x.f,x.mission,x.agencyName].filter(Boolean).join(' ').toLowerCase();return terms.every(t=>hay.includes(t)||aliases[t]&&hay.includes(aliases[t]))&&(!$('#type').value||(x.actionType||x.t)===$('#type').value)&&(!$('#result').value||x.result===$('#result').value);}).sort((a,b)=>String(b.date?.iso||b.iso||b.id).localeCompare(String(a.date?.iso||a.iso||a.id)));state.page=1;render();}
function fields(parent,pairs){const dl=el('dl',undefined,'meta');for(const [k,v] of pairs){const d=el('div');d.append(el('dt',k),el('dd',v===null||v===undefined||v===''?'未记录':v));dl.append(d);}parent.append(dl);}
async function detail(x,target){target.replaceChildren(el('p','载入详情…'));try{const r=x.vehicleDetails?x:(await yearData(x.y)).find(r=>r.id===x.id);if(!r)throw Error('没有找到详情');target.replaceChildren();fields(target,[['档案编号',r.id],['UTC原始时间',r.date?.utc],['原始时间精度',r.date?.precision],['发射场',r.siteName],['场址位置',r.siteLocation],['经度',r.longitude],['纬度',r.latitude],['发射台',r.pad],['机构',r.agencyName],['机构代码',r.agencyCode],['目的地',r.destination],['近地点 km',r.perigee],['远地点 km',r.apogee],['倾角 °',r.inclination],['航程 km',r.range],['入轨总质量 t',r.orbitalMass],['载荷质量 t',r.payloadMass],['制造机构',r.vehicleDetails?.manufacturer],['运载器家族',r.vehicleDetails?.family],['发射时间引文',r.citation],['补充引文',r.citation2],['备注',r.notes]]);if(r.rich?.purpose)target.append(el('p',r.rich.purpose));const raw=el('details');raw.append(el('summary','查看完整原始记录'),el('pre',JSON.stringify(r,null,2)));target.append(raw);}catch(e){target.replaceChildren(el('p',e.message));}}
function render(){const rows=state.filtered,pages=Math.max(1,Math.ceil(rows.length/state.size));$('#cards').replaceChildren();$('#status').textContent=`${state.mode==='all'?'全库':$('#year').value+' 年'}：${rows.length.toLocaleString()} 条结果 / 已载入 ${state.rows.length.toLocaleString()} 条`;for(const x of rows.slice((state.page-1)*state.size,state.page*state.size)){const card=el('article',undefined,'card');card.append(el('p',(x.date?.cn||x.d||'未记录')+' · UTC+8','date'),el('h2',x.flight||x.mission||x.flightCode||x.flightId||x.f||x.id));fields(card,[['运载器',x.vehicle||x.v],['机构',x.agencyName||x.a],['行动类型',x.actionType||x.t],['结果',x.result]]);const d=el('details'),body=el('div');d.append(el('summary','展开任务、轨迹及来源'),body);let loaded=false;d.addEventListener('toggle',()=>{if(d.open&&!loaded){loaded=true;detail(x,body);}});card.append(d);$('#cards').append(card);}if(!rows.length)$('#cards').append(el('p','没有符合条件的记录。'));$('#page').textContent=`第 ${state.page} / ${pages} 页`;$('#prev').disabled=state.page===1;$('#next').disabled=state.page===pages;}
$('#q').oninput=apply;$('#type').onchange=apply;$('#result').onchange=apply;$('#year').onchange=()=>load();$('#all').onclick=()=>load(true);$('#reset').onclick=()=>{$('#q').value='';$('#type').value='';$('#result').value='';apply();};for(const [id,delta] of [['#prev',-1],['#next',1]])$(id).onclick=()=>{state.page+=delta;render();$('#status').scrollIntoView();};
(async()=>{try{state.manifest=await json('archive/manifest.json');const m=state.manifest;$('#coverage').textContent=`${m.total.toLocaleString()} 条 · ${m.coverage.first}–${m.coverage.last} 年 · 来源更新时间 ${m.sourceUpdated} UTC`;for(const y of m.years)$('#year').add(new Option(`${y.year} 年（${y.count} 条）`,y.year));await load();}catch(e){$('#status').textContent=e.message;}})();
